### ISSUE TITLE
Errors when run locally due to unexpected Serverless messages

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/serverless-offline-sts#22]
To enable this library to assume the required role it makes a `call` to serverless to obtain a copy of the service configuration.
That call is to `serverless print`.  The expected output (as document here https://www.serverless.com/framework/docs/providers/aws/cli-reference/print) is the serverless.yml with all the variables resolved.

However, when run locally the output of `serverless print` is prefixed with a number of informational messages including, but not limited to:

- Serverless: Running "serverless" installed locally (in service node_modules)
- Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.

Those messages are not yaml which triggers a fail in the parsing of the output.

**Comment by GeoffThorpeFT** [comment]
There is a potential solution based on some form of pre-parse filtering of the `serverless print` stream.  Something like this in `index.js`:

```
const unwantedWarning = 'Serverless: Running "serverless" installed locally (in service node_modules)';
const readServerless = async () => {
	const serverlessYaml = await execa('serverless', ['print']);
	let geoff = await getStream(serverlessYaml.stdout);

	while (geoff.substr(0,11) === 'Serverless:') {
		geoff = geoff.substring(geoff.indexOf("\n") + 1)
	}
	return yaml.load(geoff);
};
```

**Comment by wheresrhys** [comment]
Addressed by https://github.com/Financial-Times/serverless-offline-sts/pull/26
